package com.app.ecom.init;

import com.app.ecom.model.Product;
import com.app.ecom.repository.ProductRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

@Component
@RequiredArgsConstructor
public class DataInitializer implements CommandLineRunner {

    private final ProductRepository productRepository;

    @Override
    public void run(String... args) throws Exception {
        if (productRepository.count() == 0) {
            List<Product> products = Arrays.asList(
                // Category: Smartphones (5 products)
                createProduct("Apple iPhone 15 Pro Max", "Experience the power of titanium with the new A17 Pro chip, custom Action button, and the most powerful iPhone camera system ever. Features a 6.7-inch Super Retina XDR display with ProMotion.", "1199.99", 45, "Smartphones", "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=600&q=80"),
                createProduct("Samsung Galaxy S24 Ultra", "Unleash your creativity with Galaxy AI. Equipped with a 200MP camera, built-in S Pen, Snapdragon 8 Gen 3 for Galaxy, and an ultra-durable titanium frame with a 6.8-inch QHD+ display.", "1299.99", 50, "Smartphones", "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=600&q=80"),
                createProduct("Google Pixel 8 Pro", "The all-pro phone engineered by Google. Features the advanced Google Tensor G3 chip, a fully upgraded triple camera system with macro focus, and cutting-edge AI photo editing features.", "999.00", 30, "Smartphones", "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=600&q=80"),
                createProduct("Xiaomi 14 Ultra", "Co-engineered with Leica, this flagship smartphone features a 1-inch main sensor with stepless variable aperture, Snapdragon 8 Gen 3, and a stunning WQHD+ AMOLED display.", "1099.50", 25, "Smartphones", "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80"),
                createProduct("OnePlus 12", "Smooth Beyond Belief. Boasting a Snapdragon 8 Gen 3 processor, 16GB RAM, 4th Gen Hasselblad Camera System, and revolutionary Trinity Engine for desktop-level gaming performance.", "799.99", 40, "Smartphones", "https://images.unsplash.com/photo-1565849328268-2432851fb0c8?auto=format&fit=crop&w=600&q=80"),

                // Category: Laptops (5 products)
                createProduct("Apple MacBook Air M3", "Incredibly thin and fast. The M3 chip brings even greater capabilities to the world's most popular laptop, with up to 18 hours of battery life and a stunning liquid retina display.", "1099.00", 35, "Laptops", "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=600&q=80"),
                createProduct("Dell XPS 15", "Power your passions with a high-performance 13th Gen Intel Core processor, immersive 15.6-inch OLED InfinityEdge display, and NVIDIA GeForce RTX graphics in a sleek aluminum chassis.", "1899.99", 20, "Laptops", "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=600&q=80"),
                createProduct("Lenovo ThinkPad X1 Carbon Gen 11", "The ultimate business professional laptop. Ultralight and ultra-powerful, featuring Intel vPro, legendary spill-resistant keyboard, and military-grade durability testing.", "1649.00", 28, "Laptops", "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=600&q=80"),
                createProduct("ASUS ROG Zephyrus G14", "A powerful Windows 11 gaming laptop featuring an AMD Ryzen 9 processor and NVIDIA GeForce RTX 4070 graphics in a compact, portable chassis with an AniMe Matrix LED lid display.", "1599.00", 15, "Laptops", "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=600&q=80"),
                createProduct("HP Spectre x360 Convertible", "Premium 2-in-1 laptop with a brilliant OLED touchscreen. Seamlessly transition from laptop to tablet mode, featuring an Intel Evo platform, long battery life, and an included stylus.", "1399.99", 22, "Laptops", "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=600&q=80"),

                // Category: Tablets (5 products)
                createProduct("Apple iPad Pro 12.9\" M2", "The ultimate iPad experience. Powered by the M2 chip, featuring an astonishing Liquid Retina XDR display, pro camera systems, and compatibility with Apple Pencil and Magic Keyboard.", "1099.00", 30, "Tablets", "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=600&q=80"),
                createProduct("Samsung Galaxy Tab S9 Ultra", "The new standard for premium Android tablets. A massive 14.6-inch Dynamic AMOLED 2X display, IP68 water resistance, Snapdragon 8 Gen 2, and the ultra-responsive S Pen included.", "1199.99", 18, "Tablets", "https://images.unsplash.com/photo-1589739900243-4b52cd9b104e?auto=format&fit=crop&w=600&q=80"),
                createProduct("Lenovo Tab P12 Pro", "Premium entertainment and productivity tablet. Features an 12.6-inch 120Hz AMOLED display, JBL quad speakers with Dolby Atmos, and dual-wireless capability to serve as a secondary display.", "649.99", 25, "Tablets", "https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=600&q=80"),
                createProduct("Xiaomi Pad 6", "A high-performance tablet for work and play. Features an 11-inch 144Hz WQHD+ display, Snapdragon 870 processor, quad speakers, and a massive 8840mAh battery with fast charging.", "349.99", 45, "Tablets", "https://images.unsplash.com/photo-1527698266440-12104e498b76?auto=format&fit=crop&w=600&q=80"),
                createProduct("Microsoft Surface Pro 9", "The power of a laptop with the flexibility of a tablet. Features a 13-inch PixelSense touchscreen, 12th Gen Intel Core processor, and built-in kickstand for productivity anywhere.", "999.00", 20, "Tablets", "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=600&q=80"),

                // Category: Smart Watches (5 products)
                createProduct("Apple Watch Ultra 2", "The most rugged and capable Apple Watch. Designed for outdoor adventures and athletic pursuits, featuring a titanium case, up to 36 hours of battery life, and high-precision GPS.", "799.00", 25, "Smart Watches", "https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?auto=format&fit=crop&w=600&q=80"),
                createProduct("Samsung Galaxy Watch 6 Classic", "The return of the iconic rotating bezel. Tracks your health, sleep, and workouts with advanced bio-sensors, packaged in a classic premium stainless steel watch design.", "399.99", 35, "Smart Watches", "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=600&q=80"),
                createProduct("Garmin Fenix 7 Pro Sapphire Solar", "Ultimate multisport GPS watch with solar charging. Features rugged design, scratch-resistant sapphire crystal lens, built-in LED flashlight, and advanced training metrics.", "899.99", 15, "Smart Watches", "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80"),
                createProduct("Fitbit Sense 2 Advanced Health Watch", "Manage stress, sleep better, and live healthier. Features an EDA sensor for stress tracking, ECG app, built-in GPS, and comprehensive heart health notifications.", "249.95", 50, "Smart Watches", "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?auto=format&fit=crop&w=600&q=80"),
                createProduct("Xiaomi Watch S3", "Stylish smartwatch featuring an interchangeable bezel design, 1.43-inch AMOLED display, brand new HyperOS, and comprehensive 150+ sports mode tracking with dual-band GPS.", "149.00", 60, "Smart Watches", "https://images.unsplash.com/photo-1517502884422-41eaaced0168?auto=format&fit=crop&w=600&q=80"),

                // Category: Headphones & Earbuds (5 products)
                createProduct("Sony WH-1000XM5", "Industry-leading noise canceling wireless headphones. Features two processors controlling 8 microphones, exceptional sound quality with LDAC, and up to 30 hours of battery life.", "398.00", 40, "Headphones & Earbuds", "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80"),
                createProduct("Apple AirPods Pro (2nd Gen)", "Rebuilt from the ground up for richer audio. Features active noise cancellation, adaptive transparency, personalized spatial audio, and an upgraded MagSafe charging case.", "249.00", 65, "Headphones & Earbuds", "https://images.unsplash.com/photo-1588449668338-d1517824f46e?auto=format&fit=crop&w=600&q=80"),
                createProduct("Bose QuietComfort Ultra", "Immersive spatial audio headphones with world-class noise cancellation. Features custom tune technology to auto-adjust sound to your ears and premium materials for long-wear comfort.", "429.00", 30, "Headphones & Earbuds", "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=600&q=80"),
                createProduct("JBL Live Pro 2 TWS", "True wireless active noise canceling earbuds. Features JBL Signature Sound, up to 40 hours of battery life, speed charge, IPX5 water resistance, and 6 mics for crystal clear calls.", "149.95", 80, "Headphones & Earbuds", "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80"),
                createProduct("Sennheiser Momentum True Wireless 4", "Experience the ultimate audio standard. Features high-fidelity sound, next-generation adaptive ANC, Bluetooth 5.4 with Auracast support, and a sleek ergonomic design.", "299.95", 35, "Headphones & Earbuds", "https://images.unsplash.com/photo-1608156639585-b3a032ef9689?auto=format&fit=crop&w=600&q=80"),

                // Category: Gaming (5 products)
                createProduct("Sony PlayStation 5 Console", "Experience lightning-fast loading with an ultra-high-speed SSD, deeper immersion with haptic feedback, adaptive triggers, 3D Audio, and an all-new generation of incredible games.", "499.99", 24, "Gaming", "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=600&q=80"),
                createProduct("Nintendo Switch - OLED Model", "Features a vibrant 7-inch OLED screen, a wide adjustable stand, a dock with a wired LAN port, 64 GB of internal storage, and enhanced audio in handheld and tabletop modes.", "349.99", 45, "Gaming", "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&w=600&q=80"),
                createProduct("Xbox Series X", "The fastest, most powerful Xbox ever. Explore rich new worlds with 12 teraflops of raw graphic processing power, DirectX Raytracing, custom SSD, and 4K gaming capabilities.", "499.00", 18, "Gaming", "https://images.unsplash.com/photo-1605901309584-818e25960a8f?auto=format&fit=crop&w=600&q=80"),
                createProduct("ASUS ROG Ally Handheld Gaming PC", "Play your favorite games anywhere with this Windows 11 handheld console. Powered by an AMD Ryzen Z1 Extreme processor and featuring a beautiful 120Hz Full HD touchscreen.", "699.99", 20, "Gaming", "https://images.unsplash.com/photo-1627856013091-fed6e4e30025?auto=format&fit=crop&w=600&q=80"),
                createProduct("Razer BlackShark V2 Pro", "The definitive esports gaming headset. Features Razer TriForce 50mm Titanium drivers, ultra-wideband mic, HyperSpeed wireless technology, and advanced noise isolation.", "199.99", 55, "Gaming", "https://images.unsplash.com/photo-1612287230202-1bf1d85d1bdf?auto=format&fit=crop&w=600&q=80"),

                // Category: Computer Accessories (5 products)
                createProduct("Logitech MX Master 3S Mouse", "An iconic ergonomic mouse remastered. Features Quiet Click buttons, 8K DPI any-surface tracking, and the MagSpeed electromagnetic scroll wheel for ultimate precision.", "99.99", 90, "Computer Accessories", "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=600&q=80"),
                createProduct("Corsair K70 RGB PRO Keyboard", "Mechanical gaming keyboard featuring Cherry MX Red switches, durable double-shot PBT keycaps, per-key RGB backlighting, and tournament-grade polling speeds.", "169.99", 40, "Computer Accessories", "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80"),
                createProduct("Dell UltraSharp U2723QE Monitor", "Brilliant 27-inch 4K USB-C hub monitor featuring IPS Black technology for exceptional contrast, wide color coverage, and extensive connectivity with power delivery.", "579.99", 15, "Computer Accessories", "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=600&q=80"),
                createProduct("Western Digital Black SN850X 2TB SSD", "Crush load times and dominate gameplay with PCIe Gen4 speeds up to 7,300 MB/s. Built for serious gamers looking for top-tier storage expansion.", "159.99", 60, "Computer Accessories", "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80"),
                createProduct("Anker 577 13-in-1 Thunderbolt Dock", "Expand your laptop's connectivity with Thunderbolt 3, HDMI, DisplayPort, USB-C, USB-A, Ethernet, SD card readers, and 85W laptop charging output.", "249.99", 30, "Computer Accessories", "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?auto=format&fit=crop&w=600&q=80"),

                // Category: Cameras (5 products)
                createProduct("Sony Alpha 7 IV Mirrorless Camera", "The perfect hybrid camera. Featuring a 33MP Exmor R CMOS sensor, advanced BIONZ XR processing, high-speed autofocus, and professional 4K 60p video capabilities.", "2499.99", 12, "Cameras", "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=600&q=80"),
                createProduct("Canon EOS R6 Mark II", "Versatile hybrid camera offering 24.2 megapixels, dual pixel CMOS AF II, up to 40 fps electronic shutter, 4K 60p video, and 5-axis in-body image stabilization.", "2299.00", 10, "Cameras", "https://images.unsplash.com/photo-1510127034890-ba27508e9f1c?auto=format&fit=crop&w=600&q=80"),
                createProduct("GoPro HERO12 Black", "Capture your adventures with stunning detail. Featuring HDR 5.3K video, HyperSmooth 6.0 stabilization, rugged waterproof build, and dual LCD screens.", "399.99", 45, "Cameras", "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=600&q=80"),
                createProduct("Nikon Z6 II Mirrorless Camera", "Dual processors deliver exceptional speed and processing capability for photos and video. Built with a 24.5MP BSI sensor and dual card slots.", "1999.95", 14, "Cameras", "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80"),
                createProduct("DJI Osmo Pocket 3 Creator Combo", "Pocket-sized gimbal camera with a 1-inch CMOS sensor. Features 4K/120fps video, mechanical stabilization, rotatable touchscreen, and premium wireless microphone kit.", "669.00", 22, "Cameras", "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&w=600&q=80"),

                // Category: Home Appliances (4 products)
                createProduct("Dyson V15 Detect Cordless Vacuum", "The most powerful, intelligent cordless vacuum. Laser reveals microscopic dust, automatically adapts suction power based on floor type and debris level.", "749.99", 25, "Home Appliances", "https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=600&q=80"),
                createProduct("Xiaomi Smart Air Purifier 4 Pro", "Breathe clean, fresh air. Removes 99.97% of airborne particles, neutralizes odors, and features low-noise operation with smart app control.", "229.00", 40, "Home Appliances", "https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=600&q=80"),
                createProduct("Philips Sonicare ProtectiveClean 5100", "Sonic electric toothbrush that improves gum health up to 100% compared to a manual toothbrush. Features pressure sensor and 3 brushing modes.", "99.99", 75, "Home Appliances", "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=600&q=80"),
                createProduct("LG Dual Inverter Smart Window Air Conditioner", "Energy-efficient cooling with dual inverter technology. Ultra-quiet operation, Wi-Fi control via ThinQ app, and powerful cooling for medium rooms.", "449.99", 15, "Home Appliances", "https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=600&q=80"),

                // Category: Kitchen Appliances (4 products)
                createProduct("Instant Pot Duo Plus 9-in-1", "Versatile multi-cooker replacing up to 9 kitchen appliances. Pressure cooker, slow cooker, rice cooker, steamer, sauté pan, and yogurt maker all in one.", "129.99", 60, "Kitchen Appliances", "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=600&q=80"),
                createProduct("Philips Premium Airfryer XXL", "The healthiest way to fry. Patented fat removal technology extracts excess fat, creating crispy, delicious fried foods with up to 90% less oil.", "249.95", 35, "Kitchen Appliances", "https://images.unsplash.com/photo-1621972750749-0fbb1abb7736?auto=format&fit=crop&w=600&q=80"),
                createProduct("DeLonghi Magnifica Start Espresso Machine", "Automatic espresso machine with integrated grinder. Create barista-quality espresso, coffee, and cappuccino at home with the touch of a button.", "599.99", 18, "Kitchen Appliances", "https://images.unsplash.com/photo-1517256064527-09c53b2d0bc6?auto=format&fit=crop&w=600&q=80"),
                createProduct("KitchenAid Artisan Series Stand Mixer", "The culinary icon. Features a 5-quart stainless steel bowl, 10 speeds, tilt-head design, and attachment hub to transform your mixer into a culinary hub.", "449.99", 20, "Kitchen Appliances", "https://images.unsplash.com/photo-1578643463396-0997cb5328c1?auto=format&fit=crop&w=600&q=80"),

                // Category: TVs (4 products)
                createProduct("LG C3 65\" 4K OLED Smart TV", "Experience breathtaking contrast and vibrant colors with self-lit pixels. Powered by the a9 AI Processor Gen6, featuring Dolby Vision and Atmos.", "1699.99", 15, "TVs", "https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&w=600&q=80"),
                createProduct("Samsung QN90C 55\" Neo QLED 4K TV", "Neo Quantum Matrix technology delivers ultra-precise light control. Features brilliant color, deep contrast, Dolby Atmos sound, and Smart Hub.", "1199.99", 22, "TVs", "https://images.unsplash.com/photo-1593789198777-f29bc259780e?auto=format&fit=crop&w=600&q=80"),
                createProduct("Sony Bravia XR A80L OLED TV", "Cognitive Processor XR delivers natural, immersive picture quality. Acoustic Surface Audio+ makes the screen the speaker for perfect harmony.", "1899.00", 10, "TVs", "https://images.unsplash.com/photo-1601944179066-29786cb9d32a?auto=format&fit=crop&w=600&q=80"),
                createProduct("TCL QM8 75\" Mini-LED 4K TV", "Flagship performance with thousands of mini-LED backlight zones. Exceptional brightness, QLED wide color, and built-in subwoofer sound.", "1299.99", 18, "TVs", "https://images.unsplash.com/photo-1461151304267-38cd057c7f7f?auto=format&fit=crop&w=600&q=80"),

                // Category: Audio Systems (4 products)
                createProduct("Sonos Arc Soundbar", "Bring all your entertainment to life with the premium smart soundbar. Features Dolby Atmos spatial audio, tuned by Oscar-winning sound engineers.", "899.00", 25, "Audio Systems", "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=600&q=80"),
                createProduct("JBL Bar 1000 Soundbar System", "True 3D surround sound with detachable wireless speakers, Dolby Atmos, DTS:X, and a powerful 10-inch wireless subwoofer for earth-shaking bass.", "999.95", 15, "Audio Systems", "https://images.unsplash.com/photo-1545048702-79362596cdc9?auto=format&fit=crop&w=600&q=80"),
                createProduct("Sony HT-A7000 7.1.2ch Soundbar", "Flagship soundbar with overhead sound, built-in dual subwoofers, S-Force Pro Front Surround, and room calibration for immersive home theater.", "1199.99", 12, "Audio Systems", "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=600&q=80"),
                createProduct("Bose Smart Ultra Soundbar", "Experience true dialogue clarity and dramatic spatial sound with A.I. Dialogue Mode and Dolby Atmos. Supports Wi-Fi, Bluetooth, and AirPlay 2.", "899.00", 20, "Audio Systems", "https://images.unsplash.com/photo-1545048702-79362596cdc9?auto=format&fit=crop&w=600&q=80"),

                // Category: Networking Devices (4 products)
                createProduct("ASUS RT-AX88U Pro Router", "Dual-band Wi-Fi 6 router offering speeds up to 6000Mbps. Features commercial-grade security, dual 2.5G ports, and robust AiMesh technology.", "299.99", 30, "Networking Devices", "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=600&q=80"),
                createProduct("Netgear Orbi Whole Home WiFi 6 System", "AX6000 Tri-band mesh system covering up to 5,000 sq. ft. Connect up to 100 devices with strong, reliable Wi-Fi in every corner of your home.", "699.99", 18, "Networking Devices", "https://images.unsplash.com/photo-1631553127989-13c56d289025?auto=format&fit=crop&w=600&q=80"),
                createProduct("TP-Link Deco X55 Mesh System", "Affordable 3-pack mesh system delivering Wi-Fi 6 coverage up to 6,500 sq. ft. AI-driven mesh automatically learns your network environment.", "229.99", 45, "Networking Devices", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80"),
                createProduct("Ubiquiti UniFi Dream Machine Pro", "Enterprise-grade UniFi security gateway and network appliance. Features integrated switch, 10G SFP+ ports, and scalable controller software.", "379.00", 12, "Networking Devices", "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=600&q=80"),

                // Category: Office Equipment (4 products)
                createProduct("HP LaserJet Pro MFP M428fdw", "Wireless monochrome laser printer designed for medium teams. Features fast print, copy, scan, and fax, plus robust security protection.", "499.00", 20, "Office Equipment", "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?auto=format&fit=crop&w=600&q=80"),
                createProduct("Epson EcoTank ET-2800 Inkjet Printer", "Cartridge-free printing with easy-to-fill, supersized ink tanks. Offers low cost per print and crisp quality for documents and photo prints.", "249.99", 35, "Office Equipment", "https://images.unsplash.com/photo-1563206767-5b18f218e8de?auto=format&fit=crop&w=600&q=80"),
                createProduct("Brother P-touch Label Maker", "Desktop label maker with keyboard. Choose from multiple fonts, frames, and symbols to organize your workspace and warehouse inventory.", "49.99", 80, "Office Equipment", "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&w=600&q=80"),
                createProduct("Fellowes Powershred 99Ci Paper Shredder", "Cross-cut paper shredder with 100% jam proof system. Shreds up to 18 sheets per pass into secure cross-cut particles, plus CDs and credit cards.", "329.99", 15, "Office Equipment", "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&w=600&q=80"),

                // Category: Fashion (Men/Women) (5 products)
                createProduct("Levis 501 Original Jeans", "The blueprint for every pair of jeans in existence. Made with high-quality durable cotton denim, featuring the iconic straight fit and button fly.", "79.50", 120, "Fashion (Men/Women)", "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=600&q=80"),
                createProduct("Adidas Originals Trefoil Hoodie", "A timeless everyday hoodie made from soft fleece. Features the classic embroidered trefoil logo on the chest, kangaroo pocket, and drawcord hood.", "65.00", 95, "Fashion (Men/Women)", "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=600&q=80"),
                createProduct("Nike Windrunner Windbreaker Jacket", "The legendary windbreaker jacket. Light, water-repellent ripstop fabric with chevron design lines inspired by the 1978 original running jacket.", "100.00", 85, "Fashion (Men/Women)", "https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=600&q=80"),
                createProduct("Zara Wool Blend Belted Coat", "Elegant women's wool-mix coat featuring a lapel collar, long sleeves, front pockets, and a matching fabric belt to secure a tailored silhouette.", "149.00", 40, "Fashion (Men/Women)", "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=600&q=80"),
                createProduct("Patagonia Better Sweater Fleece", "Warm, low-bulk quarter-zip pullover made with knitted polyester fleece. Fair Trade Certified sewn and dyed with a low-impact process.", "129.00", 50, "Fashion (Men/Women)", "https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=600&q=80"),

                // Category: Shoes (5 products)
                createProduct("Nike Air Max 90 Sneakers", "Nothing as fly, nothing as comfortable. The classic running shoe features visible Max Air cushioning in the heel, waffle sole, and stitched overlays.", "130.00", 110, "Shoes", "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80"),
                createProduct("Adidas Ultraboost Light Running Shoes", "Our lightest Ultraboost ever. Features energy-returning Light Boost cushioning, Primeknit upper, and Continental rubber outsole for traction.", "190.00", 75, "Shoes", "https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=600&q=80"),
                createProduct("Puma Suede Classic Sneakers", "An icon since 1968. Features a full suede upper, clean sporty lines, and comfortable rubber outsole. A staple of street culture and style.", "75.00", 90, "Shoes", "https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=600&q=80"),
                createProduct("ASICS Gel-Kayano 30", "Premium stability running shoes. Features a 4D Guidance System to assist transition and plush FF Blast Plus Eco cushioning for premium comfort.", "160.00", 60, "Shoes", "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=600&q=80"),
                createProduct("Birkenstock Arizona Eva Sandals", "The classic two-strap sandal made from ultra-lightweight and highly flexible EVA material. Waterproof, washable, and shock-absorbent.", "49.95", 130, "Shoes", "https://images.unsplash.com/photo-1603808033192-082d6f74b30e?auto=format&fit=crop&w=600&q=80"),

                // Category: Bags (4 products)
                createProduct("Samsonite Omni 2 Hardside Luggage", "Extremely lightweight and scratch-resistant polycarbonate spinner luggage. Features 360-degree dual spinner wheels and TSA-approved locks.", "159.99", 45, "Bags", "https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?auto=format&fit=crop&w=600&q=80"),
                createProduct("Fjallraven Kanken Classic Backpack", "The iconic Scandinavian backpack. Made from durable, water-resistant Vinylon F fabric. Features a spacious main compartment and supportive foam insert.", "89.95", 80, "Bags", "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80"),
                createProduct("Herschel Heritage Backpack", "A classic design updated for modern utility. Features signature striped fabric liner, internal laptop sleeve, and front storage pocket with key clip.", "64.99", 90, "Bags", "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=600&q=80"),
                createProduct("Peak Design Everyday Backpack V2", "Award-winning versatile camera and laptop backpack. Features customizable FlexFold dividers, weatherproof zippers, and multi-access points.", "279.90", 25, "Bags", "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80"),

                // Category: Beauty & Personal Care (5 products)
                createProduct("Estee Lauder Advanced Night Repair", "Revolutionary nightly repair serum for visible youth-generating power. Significantly reduces the look of key signs of aging and hydrates skin.", "85.00", 70, "Beauty & Personal Care", "https://images.unsplash.com/photo-1608248597481-496100c8c836?auto=format&fit=crop&w=600&q=80"),
                createProduct("Dyson Airwrap Multi-Styler", "Style your hair with air, not extreme heat. Features engineered barrels and brushes to curl, wave, smooth, and dry hair with no heat damage.", "599.99", 15, "Beauty & Personal Care", "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=600&q=80"),
                createProduct("Clinique Moisture Surge 100H", "Refreshing gel-cream hydrator with exclusive aloe bio-ferment and hyaluronic acid. Penetrates deep, lasting for 100 hours of continuous moisture.", "45.00", 85, "Beauty & Personal Care", "https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?auto=format&fit=crop&w=600&q=80"),
                createProduct("Philips Lumea Prestige IPL Hair Removal", "Achieve hair-free smooth skin for up to 6 months. SmartSkin sensor guides the IPL pulses, featuring curved attachments for different body zones.", "399.00", 20, "Beauty & Personal Care", "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=600&q=80"),
                createProduct("CeraVe Hydrating Facial Cleanser", "Gentle non-foaming face wash developed with dermatologists. Formulated with three essential ceramides and hyaluronic acid to protect the skin barrier.", "15.99", 150, "Beauty & Personal Care", "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80"),

                // Category: Sports Equipment (5 products)
                createProduct("Wilson Evolution Indoor Basketball", "The preferred game basketball in high schools nationwide. Signature micro-fiber composite cover delivers excellent grip and control.", "79.95", 65, "Sports Equipment", "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=600&q=80"),
                createProduct("Nike Pitch Soccer Ball", "Designed for training and recreational play. Smooth casing offers consistent touch, while high-contrast graphics make the ball easy to track.", "25.00", 100, "Sports Equipment", "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=600&q=80"),
                createProduct("Titleist Pro V1 Golf Balls (Dozen)", "The #1 ball in golf. Provides total performance, longer distance, low long-game spin, high drop-and-stop control, and soft feel.", "55.00", 110, "Sports Equipment", "https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?auto=format&fit=crop&w=600&q=80"),
                createProduct("Bowflex SelectTech 552 Dumbbells", "Adjustable dumbbells replacing 15 sets of weights. Turn the dial to easily adjust weight from 5 to 52.5 lbs for an efficient home workout.", "429.00", 24, "Sports Equipment", "https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?auto=format&fit=crop&w=600&q=80"),
                createProduct("Fitbit Aria Air Smart Scale", "Easy-to-use smart scale that measures weight and syncs it to the Fitbit app via Bluetooth, allowing you to track your BMI and weight trends.", "49.95", 70, "Sports Equipment", "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80"),

                // Category: Books (4 products)
                createProduct("Atomic Habits by James Clear", "The definitive guide to breaking bad behaviors and creating good habits. Learn the science of tiny changes and how they yield remarkable results.", "17.99", 140, "Books", "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=600&q=80"),
                createProduct("The Psychology of Money by Morgan Housel", "Timeless lessons on wealth, greed, and happiness. Explore how personal behavior shapes financial success far more than intelligence or math.", "16.50", 120, "Books", "https://images.unsplash.com/photo-1592496431122-2349e0fbc666?auto=format&fit=crop&w=600&q=80"),
                createProduct("Dune Deluxe Edition by Frank Herbert", "The masterpiece of sci-fi storytelling. Follow young Paul Atreides on the desert planet Arrakis in a gorgeous hardcover collectible edition.", "30.00", 50, "Books", "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=600&q=80"),
                createProduct("Sapiens: A Brief History of Humankind", "Dr. Yuval Noah Harari spans the whole of human history, from the first humans to walk the earth to the radical breakthroughs of the modern age.", "19.99", 95, "Books", "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=600&q=80"),

                // Category: Toys (4 products)
                createProduct("LEGO Star Wars Millennium Falcon", "Build the legendary Corellian smuggler ship. Features rotating gun turrets, dual spring-loaded shooters, lowering ramp, and 7 minifigures.", "169.99", 30, "Toys", "https://images.unsplash.com/photo-1585366119957-e5733f3000cd?auto=format&fit=crop&w=600&q=80"),
                createProduct("Barbie Dreamhouse Playset", "The ultimate three-story doll house featuring 10 indoor and outdoor play areas, customizable slide, pool, and working lights and sounds.", "199.99", 20, "Toys", "https://images.unsplash.com/photo-1559251606-c623743a6d76?auto=format&fit=crop&w=600&q=80"),
                createProduct("Hasbro Monopoly Deal Card Game", "All the fun of Monopoly in a fast-paced card game. Collect properties, charge rent, and execute sly deals in just 15 minutes of play.", "7.99", 150, "Toys", "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=600&q=80"),
                createProduct("DJI Tello Mini Drone for Kids", "The perfect entry-level drone. Perform flying stunts, shoot quick videos with EZ Shots, and learn coding basics with Scratch programming.", "99.00", 50, "Toys", "https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=600&q=80"),

                // Category: Furniture (4 products)
                createProduct("Herman Miller Aeron Ergonomic Chair", "The gold standard in office seating. Features patented PostureFit SL back support, breathable Pellicle suspension, and fully adjustable armrests.", "1295.00", 15, "Furniture", "https://images.unsplash.com/photo-1580481072645-022f9a6dbf27?auto=format&fit=crop&w=600&q=80"),
                createProduct("IKEA Billy Bookcase", "A versatile classic bookcase. Clean lines and adjustable shelves make it suitable for living rooms, offices, libraries, or storage areas.", "89.00", 60, "Furniture", "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=600&q=80"),
                createProduct("Ashley Furniture Modern Sofa", "Contemporary three-seater sofa featuring soft fabric upholstery, thick supportive foam cushions, and a durable solid hardwood frame.", "599.99", 12, "Furniture", "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=600&q=80"),
                createProduct("Philips Hue Smart LED Floor Lamp", "Bring beautiful gradient color to any room. Syncs with music, movies, or games for an immersive dynamic lighting ambiance via app control.", "219.99", 25, "Furniture", "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=80")
            );

            productRepository.saveAll(products);
            System.out.println(">> Database seeded successfully with 100 products!");
        }
    }

    private Product createProduct(String name, String description, String price, Integer stockQuantity, String category, String imageUrl) {
        Product product = new Product();
        product.setName(name);
        product.setDescription(description);
        product.setPrice(new BigDecimal(price));
        product.setStockQuantity(stockQuantity);
        product.setCategory(category);
        product.setImageUrl(imageUrl);
        product.setActive(true);
        return product;
    }
}
